local ai = require("mini.ai")

return {
	"echasnovski/mini.nvim",
	version = "*",
	ai.setup({
		custom_textobjects = {
			s = { "%[%[().-()%]%]" },
			F = ai.gen_spec.treesitter({ a = "@function.outer", i = "@function.inner" }),
		},
	}),
	require("mini.align").setup(),
	require("mini.comment").setup(),
	require("mini.completion").setup(),
	require("mini.move").setup(),
	require("mini.operators").setup(),
	require("mini.pairs").setup(),
	require("mini.snippets").setup(),
	require("mini.splitjoin").setup(),
	require("mini.surround").setup({
		custom_surroundings = {
			s = { input = { "%[%[().-()%]%]" }, output = { left = "[[", right = "]]" } },
			c = { input = { "%[%[().-()%]%]" }, output = { left = "{{", right = "}}" } },
			p = { input = { "%[%[().-()%]%]" }, output = { left = "((", right = "))" } },
			a = { input = { "%[%[().-()%]%]" }, output = { left = "<<", right = ">>" } },
		},
	}),
	require("mini.basics").setup(),
	require("mini.bracketed").setup(),
	require("mini.bufremove").setup(),
	require("mini.clue").setup(),
	require("mini.diff").setup(),
	require("mini.extra").setup(),
	require("mini.git").setup(),
	require("mini.files").setup(),
	require("mini.jump").setup(),
	require("mini.jump2d").setup(),
	require("mini.misc").setup(),
	require("mini.pick").setup(),
	require("mini.sessions").setup(),
	require("mini.visits").setup(),
	require("mini.animate").setup(),
	require("mini.colors").setup(),
	require("mini.cursorword").setup(),
	require("mini.hipatterns").setup(),
	require("mini.icons").setup(),
	require("mini.indentscope").setup(),
	require("mini.map").setup(),
	require("mini.notify").setup(),
	require("mini.starter").setup({
		footer = os.date(),
		header = table.concat({
			[[                                   ]],
			[[                                   ]],
			[[                                   ]],
			[[   ⣴⣶⣤⡤⠦⣤⣀⣤⠆     ⣈⣭⣿⣶⣿⣦⣼⣆          ]],
			[[    ⠉⠻⢿⣿⠿⣿⣿⣶⣦⠤⠄⡠⢾⣿⣿⡿⠋⠉⠉⠻⣿⣿⡛⣦       ]],
			[[          ⠈⢿⣿⣟⠦ ⣾⣿⣿⣷    ⠻⠿⢿⣿⣧⣄     ]],
			[[           ⣸⣿⣿⢧ ⢻⠻⣿⣿⣷⣄⣀⠄⠢⣀⡀⠈⠙⠿⠄    ]],
			[[          ⢠⣿⣿⣿⠈    ⣻⣿⣿⣿⣿⣿⣿⣿⣛⣳⣤⣀⣀   ]],
			[[   ⢠⣧⣶⣥⡤⢄ ⣸⣿⣿⠘  ⢀⣴⣿⣿⡿⠛⣿⣿⣧⠈⢿⠿⠟⠛⠻⠿⠄  ]],
			[[  ⣰⣿⣿⠛⠻⣿⣿⡦⢹⣿⣷   ⢊⣿⣿⡏  ⢸⣿⣿⡇ ⢀⣠⣄⣾⠄   ]],
			[[ ⣠⣿⠿⠛ ⢀⣿⣿⣷⠘⢿⣿⣦⡀ ⢸⢿⣿⣿⣄ ⣸⣿⣿⡇⣪⣿⡿⠿⣿⣷⡄  ]],
			[[ ⠙⠃   ⣼⣿⡟  ⠈⠻⣿⣿⣦⣌⡇⠻⣿⣿⣷⣿⣿⣿ ⣿⣿⡇ ⠛⠻⢷⣄ ]],
			[[      ⢻⣿⣿⣄   ⠈⠻⣿⣿⣿⣷⣿⣿⣿⣿⣿⡟ ⠫⢿⣿⡆    ]],
			[[       ⠻⣿⣿⣿⣿⣶⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⢀⣀⣤⣾⡿⠃    ]],
			[[                                  ]],
		}, "\n"),
	}),
	require("mini.trailspace").setup(),
	require("mini.doc").setup(),
	require("mini.fuzzy").setup(),
	require("mini.test").setup(),
}
